In [21]:
import pandas as pd
import numpy as np
import networkx as nx
import graph as gr
import utils as ut
import feature_selection as fs
import classification as cl
import os.path
import matplotlib.pyplot as plt
from sklearn import preprocessing
import importlib
import community
import seaborn as sns
from gensim.models import KeyedVectors
from pyemd import emd
from gensim import corpora
from nltk.corpus import stopwords
from gensim.matutils import softcossim

In [281]:
importlib.reload(fs)

<module 'feature_selection' from 'C:\\Users\\faisal\\PycharmProjects\\linkPrediction\\feature_selection.py'>

In [4]:
word_vectors = KeyedVectors.load_word2vec_format('pubmed2018_w2v_200D/pubmed2018_w2v_200D.bin', binary=True)

In [23]:
filepath=['dataset/apnea-all,3.csv',
         'dataset/apnea-distinct_keyword.csv']
graphpath='C:/Users/faisal/PycharmProjects/linkPrediction/graphs'
column_split=['keyword','author_name','affiliation_1','affiliation_2','country']
#time=[parent_start_year, train_start_year, test_start_year, total_test_period_in_year, total_year_in_each_iteration]
time=[1980,1991,2004,1,1]
df, key_list = ut.load_dataset(filepath, column_split)

In [14]:
#dynamic train graphs and test graph build and save in disk 
gr.dynamic_train_test_graph_build(df, key_list, graphpath, time)

447
C:/Users/faisal/PycharmProjects/linkPrediction/graphs\train_graph_1991.gpickle saved, nodes: 54 edges: 60
C:/Users/faisal/PycharmProjects/linkPrediction/graphs\train_graph_1992.gpickle saved, nodes: 64 edges: 68
C:/Users/faisal/PycharmProjects/linkPrediction/graphs\train_graph_1993.gpickle saved, nodes: 75 edges: 88
C:/Users/faisal/PycharmProjects/linkPrediction/graphs\train_graph_1994.gpickle saved, nodes: 93 edges: 76
C:/Users/faisal/PycharmProjects/linkPrediction/graphs\train_graph_1995.gpickle saved, nodes: 132 edges: 170
C:/Users/faisal/PycharmProjects/linkPrediction/graphs\train_graph_1996.gpickle saved, nodes: 155 edges: 219
C:/Users/faisal/PycharmProjects/linkPrediction/graphs\train_graph_1997.gpickle saved, nodes: 147 edges: 158
C:/Users/faisal/PycharmProjects/linkPrediction/graphs\train_graph_1998.gpickle saved, nodes: 149 edges: 180
C:/Users/faisal/PycharmProjects/linkPrediction/graphs\train_graph_1999.gpickle saved, nodes: 165 edges: 163
C:/Users/faisal/PycharmProjects/

In [25]:
#load all graphs
g_train, g_test, g_parent, g_train_static, g_test_static = gr.graph_load(graphpath, time)

C:/Users/faisal/PycharmProjects/linkPrediction/graphs\train_graph_1991.gpickle loaded, nodes: 54 edges: 60
C:/Users/faisal/PycharmProjects/linkPrediction/graphs\train_graph_1992.gpickle loaded, nodes: 64 edges: 68
C:/Users/faisal/PycharmProjects/linkPrediction/graphs\train_graph_1993.gpickle loaded, nodes: 75 edges: 88
C:/Users/faisal/PycharmProjects/linkPrediction/graphs\train_graph_1994.gpickle loaded, nodes: 93 edges: 76
C:/Users/faisal/PycharmProjects/linkPrediction/graphs\train_graph_1995.gpickle loaded, nodes: 132 edges: 170
C:/Users/faisal/PycharmProjects/linkPrediction/graphs\train_graph_1996.gpickle loaded, nodes: 155 edges: 219
C:/Users/faisal/PycharmProjects/linkPrediction/graphs\train_graph_1997.gpickle loaded, nodes: 147 edges: 158
C:/Users/faisal/PycharmProjects/linkPrediction/graphs\train_graph_1998.gpickle loaded, nodes: 149 edges: 180
C:/Users/faisal/PycharmProjects/linkPrediction/graphs\train_graph_1999.gpickle loaded, nodes: 165 edges: 163
C:/Users/faisal/PycharmProj

In [207]:
train_data, train_data_static, parent_data, test_data_static = cl.non_edge_feature_dataframe(g_train, 
                                                                                             g_test,
                                                                                             g_parent,
                                                                                             g_train_static, 
                                                                                             g_test_static,  
                                                                                             time, 
                                                                                             freq=10)

parent
positive train: 102 negative train: 3894 train_size: 3996
train
positive train: 416 negative train: 97676 train_size: 98092
train
positive train: 416 negative train: 4160 train_size: 4576
train
positive train: 32 negative train: 51 train_size: 83
train
positive train: 25 negative train: 75 train_size: 100
train
positive train: 30 negative train: 104 train_size: 134
train
positive train: 49 negative train: 185 train_size: 234
train
positive train: 78 negative train: 342 train_size: 420
train
positive train: 120 negative train: 468 train_size: 588
train
positive train: 98 negative train: 439 train_size: 537
train
positive train: 112 negative train: 441 train_size: 553
train
positive train: 106 negative train: 544 train_size: 650
train
positive train: 130 negative train: 637 train_size: 767
train
positive train: 133 negative train: 869 train_size: 1002
train
positive train: 139 negative train: 745 train_size: 884
train
positive train: 176 negative train: 1007 train_size: 1183
test


In [282]:
#parent keys for 1st year
parent_keys = fs.parent_key_from_parent_graph(df, key_list, g_parent, g_train, time)

dist_aut_art: 3.1657091642888293 dist_y_weight: 4.822365429261176


In [336]:
importlib.reload(fs)
node_feature, train_data = fs.dynamic_graph_feature_set(df, key_list, train_data, g_parent, g_train, g_train_static, time)

dist_aut_art: 3.1657091642888293 dist_y_weight: 4.822365429261176


In [351]:
list(train_data[1991].iloc[0,1:10])

[1,
 0.7563048926997847,
 -0.6739360184961675,
 0.28922542204568025,
 0,
 0.02197802197802198,
 10,
 0.2,
 0]

In [347]:
train_data[1991].head()

row_name  label       aut       art  closeness  partition  y_weight  \
0  (8833, 10649)      1  0.756305 -0.673936   0.289225          0  0.021978   
1    (801, 8833)      1  0.590667 -0.739428   0.308265          0  0.021978   
2  (8833, 12485)      0 -1.440064 -0.778896   0.292830          0  0.021978   
3  (8833, 12542)      1 -9.011196 -9.059030   0.475472          0  0.021978   
4  (2451, 14850)      0  0.272993 -0.846771   0.220937          0  0.021978   

   type  partition_cnt  path_len3  
0    10       0.200000          0  
1     6       0.166667          0  
2    10       0.300000          0  
3    10       1.000000          0  
4     6       0.166667          0

In [394]:
ts = time[1]
te = time[2]
it_index = time[4]
edge_set = set()
for t in range(ts,te, it_index):
    edge_set.update(train_data[t]['row_name'])
len(edge_set)

3141

In [442]:
ts = time[1]
te = time[2]
it_index = time[4]
time_range = te-ts
feature = np.zeros([1,time_range,9])
feature.shape
ed = tuple((8833, 12542))
for t in range(ts,te, it_index):
    if ed in set(train_data[t]['row_name']):
        #print(len(train_data[t].iloc[0]))
        tt = np.asarray(train_data[t].loc[train_data[t]['row_name']==ed].values[0][1:10])
        print(tt, t)
        feature[0][t-ts]=tt
    else:
        tt = np.zeros(9,dtype=float)
        print(tt,t)
        feature[0][t-ts]=tt

[1 -9.011195982467889 -9.059029895110744 0.4754716981132075 0
 0.02197802197802198 10 1.0 0] 1991
[0. 0. 0. 0. 0. 0. 0. 0. 0.] 1992
[0. 0. 0. 0. 0. 0. 0. 0. 0.] 1993
[0. 0. 0. 0. 0. 0. 0. 0. 0.] 1994
[1 -7.800920590378357 -8.82823366519218 0.3324080499653019 0
 0.0670249015670459 10 0.9285714285714285 0] 1995
[0. 0. 0. 0. 0. 0. 0. 0. 0.] 1996
[0. 0. 0. 0. 0. 0. 0. 0. 0.] 1997
[0. 0. 0. 0. 0. 0. 0. 0. 0.] 1998
[0. 0. 0. 0. 0. 0. 0. 0. 0.] 1999
[0. 0. 0. 0. 0. 0. 0. 0. 0.] 2000
[0. 0. 0. 0. 0. 0. 0. 0. 0.] 2001
[0. 0. 0. 0. 0. 0. 0. 0. 0.] 2002
[1 -0.08102310846836398 -10.400958388496278 0.2953581566204709 0
 0.15688649243091138 10 0.8518518518518519 0] 2003


In [445]:
from pylab import *
from pprint import pprint


def arrayToList(arr):
    if type(arr) == type(array([])):
        return arrayToList(arr.tolist())
    elif type(arr) == type([]):
        return [arrayToList(a) for a in arr]
    else:
        return arr

In [447]:
pprint(arrayToList(feature))

[[[1.0,
   -9.011195982467889,
   -9.059029895110744,
   0.4754716981132075,
   0.0,
   0.02197802197802198,
   10.0,
   1.0,
   0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.0,
   -7.800920590378357,
   -8.82823366519218,
   0.3324080499653019,
   0.0,
   0.0670249015670459,
   10.0,
   0.9285714285714285,
   0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.0,
   -0.08102310846836398,
   -10.400958388496278,
   0.2953581566204709,
   0.0,
   0.15688649243091138,
   10.0,
   0.8518518518518519,
   0.0]]]
